version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: thingspeak
      MYSQL_DATABASE: thingspeak
      MYSQL_USER: thingspeak
      MYSQL_PASSWORD: thingspeak
  app:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db